# Generated by Django 3.1.4 on 2020-12-08 22:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('summery', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TutorialSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Series', models.CharField(max_length=200)),
                ('Summery', models.CharField(max_length=200)),
                ('Category', models.ForeignKey(default='some string', on_delete=django.db.models.deletion.SET_DEFAULT, to='web.tutorialcategory', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=200)),
                ('Date_Published', models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 9, 1, 47, 35, 376406))),
                ('Contant', tinymce.models.HTMLField()),
                ('Tutorial_slug', models.CharField(max_length=200)),
                ('Tutorial_Series', models.ForeignKey(default='some string', on_delete=django.db.models.deletion.SET_DEFAULT, to='web.tutorialseries', verbose_name='Series')),
            ],
        ),
    ]
