# Generated by Django 3.1.2 on 2020-12-04 09:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tittle', models.CharField(max_length=200)),
                ('Date_Published', models.DateTimeField()),
                ('Contant', tinymce.models.HTMLField()),
            ],
        ),
    ]
