# Generated by Django 3.1.4 on 2020-12-08 22:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='Date_Published',
            field=models.DateTimeField(verbose_name=datetime.datetime(2020, 12, 9, 1, 51, 26, 79439)),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Tutorial_Series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='web.tutorialseries', verbose_name='Series'),
        ),
    ]
